# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-17 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_questionbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('choice1', models.CharField(max_length=1000)),
                ('choice2', models.CharField(max_length=1000)),
                ('choice3', models.CharField(max_length=1000)),
                ('choice4', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionBank',
        ),
    ]
