# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-21 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20170821_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice1',
            new_name='choice',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice4',
        ),
    ]
