# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-21 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_remove_choice_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice1',
            field=models.CharField(blank='True', help_text='This is 1st choice', max_length=1000),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice2',
            field=models.CharField(blank='True', help_text='This is 2nd choice', max_length=1000),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice3',
            field=models.CharField(blank='True', help_text='This is 3rd choice', max_length=1000),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice4',
            field=models.CharField(blank='True', help_text='This is 4th choice', max_length=1000),
        ),
    ]
