# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-23 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_auto_20170821_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choiceformore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(blank='True', help_text='This is 1st choice', max_length=1000)),
                ('choice2', models.CharField(blank='True', help_text='This is 2nd choice', max_length=1000)),
                ('choice3', models.CharField(blank='True', help_text='This is 3rd choice', max_length=1000)),
                ('choice4', models.CharField(blank='True', help_text='This is 4th choice', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='choiceformore',
            name='ques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.QuestionMore'),
        ),
    ]
