# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-30 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20170823_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=1000)),
                ('lastname', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('suggestions', models.CharField(max_length=20000)),
            ],
        ),
    ]
