# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-05 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_auto_20170901_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=1000)),
                ('lastname', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=2000)),
                ('subject', models.CharField(max_length=5000)),
            ],
        ),
    ]
