# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-07 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=1000)),
                ('text', models.CharField(max_length=10000)),
            ],
        ),
    ]
