# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='firstname',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='suggestions',
            field=models.TextField(max_length=20000),
        ),
    ]
