# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_auto_20171028_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleoption',
            name='answer',
            field=models.CharField(blank='True', max_length=500),
        ),
    ]
