# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0017_singleoption_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morethanone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('pub', models.DateTimeField(verbose_name='Date Published')),
                ('choice1', models.CharField(blank='True', max_length=500)),
                ('choice2', models.CharField(blank='True', max_length=500)),
                ('choice3', models.CharField(blank='True', max_length=500)),
                ('choice4', models.CharField(blank='True', max_length=500)),
                ('answer', models.CharField(blank='True', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='choiceformore',
            name='ques',
        ),
        migrations.DeleteModel(
            name='Choiceformore',
        ),
        migrations.DeleteModel(
            name='QuestionMore',
        ),
    ]
