# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0019_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pub',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of notification'),
        ),
    ]
