# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_auto_20171101_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
